Completed task 2 from homework 1
Salvatore112/SPBU-Homeworks-Programming pull request #1
Opened 2022-09-21 23:43 UTC by Salvatore112

2022-09-26 21:13 UTC, Lozov-Petr requested changes

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task2.c
> +    int devident;
Не инициализированы переменные (уже говорил об этом).

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task2.c
> +        devident-=deviser;
Пробелы

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task2.c
> +    initialDevident-=quotient;
Пробелы

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task2.c
> +        initialDevident-=deviser;
Пробелы

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task2.c
> +    if(devidentIsNegative == false && deviserIsNegative == false)
Ох.
Во-первых, вместо `bool_var == true` нужно писать `bool_var`, и вместо `bool_var == false` нужно писать `!bool_var`. Сравни свои варианты с предлагаемыми, подумай, что проще для понимания и не содержит тавтологии.
Во-вторых,  вместо 4 условных операторов можно обойтись двумя, если отдельно прибавить единицу к ответу, отдельно определить знак.

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task3.c
> +    int m;
не инициализированы переменные.

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task3.c
> +    for(int i = 0; i < (m + n); i++)
Скобки избыточны. ПОчитай про приоритеты операций в языке C.

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task3.c
> +    reverse(array, n, (n + m));
Избыточные скобки

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task3.c
> +    for(int i = begining; i < (end + begining)/2; i++)
Пробелы вокруг деления

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task4.c
> +#include <stdio.h>
Засчитано

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task5.c
> +int isBalanced(char s[])
Результат фактически является булевым значением. Используй тип bool из stdbool.

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task5.c
> +                if(stack[stackPosition] == '(' && stackPosition >= 0)
4 раза повторяется один и тот же код. Вынеси его в отдельную функцию.

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task5.c
> +    printf("Please enter a string: ");
Ещё раз. Укажи в сообщении для пользователя, что строка должна быть не более 1000 символов.
Причем константу 1000 вынеси в define.

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task6.c
> +            if(s[i+j]!=s1[j])
пробелы

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task6.c
> +    int check = 0;
Эта переменная должна быть типа bool. И в коде используй true, false и отрицание (`!bool_var`).

2022-09-26 21:13 UTC, Lozov-Petr commented on Homework1/task8.c
> +#include <stdio.h>
Зачтена

2022-11-09 09:07 UTC, yurii-litvinov requested changes
swap, счастливые билеты и подсчёт нулевых элементов в массиве зачтены, остальные надо немного поправить

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task1.c
>      double x;
Подозреваю, что этот файл не нужен

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task2.c
> +    int devident = 0;
Он dividend

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task2.c
> +int partialDevident(int devident, int deviser);
Наверное, partialQuotient --- просили ведь неполное частное

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task2.c
> +    int deviser = 0;
divisor. Если не уверены в переводах терминов, можно пойти в английскую википедию и посмотреть, я часто так сам делаю

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task2.c
> +    }
Мм, _два_ цикла деления? Можно проще

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task2.c
> +    if (!devidentIsNegative && !deviserIsNegative || devidentIsNegative && deviserIsNegative) {
Ну то есть `devidentIsNegative == deviserIsNegative` :)

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task2.c
> +    }
И тогда всю эту конструкцию можно записать как `bool answerNegative = devidentIsNegative != deviserIsNegative;` (то есть, буквально, "ответ отрицательный, когда делимое и делитель разных знаков") :)

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task2.c
> +       else {
```suggestion
       } else {

```

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task2.c
> +    if (!answerNegative) {
Это не надо, мы выше исчерпали остальные варианты. А так наоборот, смущаете компилятор --- если ни один из if-ов не выполнился, функция непонятно что возвращает

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task3.c
> +void display(int ar[], int size);
ar как имя переменной нельзя

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task3.c
> +void reverse(int array[], int begining, int end);
```suggestion
void reverse(int array[], int beginning, int end);

```

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task3.c
> +    int *array = malloc( (m + n) * sizeof(int));
```suggestion
    int *array = malloc((m + n) * sizeof(int));
```

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task3.c
> +}
Кажется, array утечёт

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task3.c
> +    int tempVal;
Неинициализированная переменная, объявленная раньше времени

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task4.c
> +                arraySums[i + j + k] += 1;
Я бы написал `++arraySums[i + j + k];`, но ладно :)

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task5.c
> +bool isBalanced(char s[]) {
s как имя параметра не годится, стайлгайд вообще запрещает имена короче 4-х символов, если это не i и j или что-то такое.

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task5.c
> +    for (int i = 0; i < strlen(s); i++) {
strlen будет перевычисляться на каждой итерации, получите квадратичную трудоёмкость вместо линейной

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task5.c
> +            break;
```suggestion
                stackPosition++;
                stack[stackPosition] = s[i];
                break;

```

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task5.c
> +    return false;
```suggestion
    return stackPosition == -1;
```

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task5.c
> +    if (stack[*stackPosition] == openBracket && *stackPosition >= 0) {
А вот бы поменять местами эти два условия, потому что если *stackPosition меньше 0, то к стеку обращаться --- плохая идея

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task5.c
> +    printf("Please enter a string(less or equal to 1000 characters): ");
```suggestion
    printf("Please enter a string (less or equal to 1000 characters): ");
```

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task6.c
> +    bool check = false;
Плохое имя переменной. check что?

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task6.c
> +            if (s[i + j] != s1[j]) {
Уверены, что s[i + j] существует? :)

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task7.c
> +    for (int i = 2; i <= round(sqrtNum); i++) {
sqrtNum целочтисленное, зачем round?

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task7.c
> +int isPrime(int num) {
Это должна быть булевая функция

2022-11-09 09:07 UTC, yurii-litvinov commented on Homework1/task7.c
> +    if(number <= 1) {
```suggestion
    if (number <= 1) {
```

2022-11-09 21:32 UTC, Salvatore112 commented on Homework1/task3.c
> +}
Что с нима будет?

2022-12-02 20:11 UTC, merged